'use strict';

angular.module('widgetApp')
    .service('widgetService', function widgetService() {

        var catalogData = {
            widgets: [],
            html: ''
        };

        this.getWidgetList = function() {
            return {
                'data':
                    [
                        {'id':1309,'productName':'MongoDB','providerURL':'http://www.mongodb.org','productVersion':'2.0.4','title':'Launch MongoDB','youtubeVideoUrl':'http://www.youtube.com/embed/w5qr4sx5Vt0','recipeURL':'http://s3.amazonaws.com/cloudify-widget/2.7/mongodb.zip','allowAnonymous':null,'apiKey':'19cc4872-2f5f-11e3-9dfa-02163e4a1592','enabled':true,'recipeName':'mongod','requireLogin':false,'loginVerificationUrl':null,'webServiceKey':null,'lifeExpectancy':3600000,'description':'This is description for Mongo player','consoleUrlService':null,'username':'hpdemo@gigaspaces.com','numOfInstances':2,'requiresLogin':false,'consolename':'Mongo Web Console','consoleurl':'http://$HOST:11001','rootpath':'','instances':[{'recipeType':'SERVICE','servicePublicIp':null,'installName':'mongod','link':{'title':'Mongo Web Console','url':'http://15.185.243.26:11001'},'corrupted':false,'instanceId':'2268737','publicIP':'15.185.243.26'},{'recipeType':'SERVICE','servicePublicIp':null,'installName':'mongod','link':{'title':'Mongo Web Console','url':'http://15.185.249.83:11001'},'corrupted':false,'instanceId':'2268747','publicIP':'15.185.249.83'}]},
                        {'id':1310,'productName':'Petclinic-Simple','providerURL':'http://www.cloudifysource.org/','productVersion':'0.1','title':'Petclinic simple application example','youtubeVideoUrl':'http://www.youtube.com/embed/anvYieQij94','recipeURL':'http://s3.amazonaws.com/cloudify-widget/2.7/petclinic-simple.zip','allowAnonymous':null,'apiKey':'19cc4ab6-2f5f-11e3-9dfa-02163e4a1592','enabled':true,'recipeName':'petclinic','requireLogin':false,'loginVerificationUrl':null,'webServiceKey':null,'lifeExpectancy':3600000,'description':'this is a description for petclinic player','consoleUrlService':'tomcat','username':'hpdemo@gigaspaces.com','numOfInstances':0,'requiresLogin':false,'consolename':'PetClinic','consoleurl':'http://$HOST:8080/petclinic','rootpath':'','instances':[]},
                        {'id':1311,'productName':'Couchbase','providerURL':'http://www.couchbase.com','productVersion':'2.0.0','title':'Launch Couchbase','youtubeVideoUrl':'http://www.youtube.com/embed/VkQ3ppHeGX4','recipeURL':'http://s3.amazonaws.com/cloudify-widget/2.7/couchbase-2.0.zip','allowAnonymous':null,'apiKey':'19cc4b60-2f5f-11e3-9dfa-02163e4a1592','enabled':true,'recipeName':'couchbase','requireLogin':false,'loginVerificationUrl':null,'webServiceKey':null,'lifeExpectancy':3600000,'description':'this is a description for couchbase player','consoleUrlService':null,'username':'hpdemo@gigaspaces.com','numOfInstances':0,'requiresLogin':false,'consolename':'Couchbase Console','consoleurl':'http://$HOST:8091','rootpath':'','instances':[]},
                        {'id':1312,'productName':'MySQL','providerURL':'http://www.mysql.com/','productVersion':'5.*','title':'MySQL','youtubeVideoUrl':'http://www.youtube.com/embed/6Li_lCZXaKY','recipeURL':'https://s3.amazonaws.com/cloudify-widget/2.7/mysql.zip','allowAnonymous':null,'apiKey':'19cc4bec-2f5f-11e3-9dfa-02163e4a1592','enabled':true,'recipeName':'mysql','requireLogin':false,'loginVerificationUrl':null,'webServiceKey':null,'lifeExpectancy':3600000,'description':'A recipe for MySQL which is the worlds most popular open source database','consoleUrlService':null,'username':'hpdemo@gigaspaces.com','numOfInstances':0,'requiresLogin':false,'consolename':'MySQL','consoleurl':'http://$HOST:3306','rootpath':'','instances':[]},
                        {'id':1313,'productName':'JBoss','providerURL':'http://www.jboss.org','productVersion':'7.1.0.Final','title':'JBoss 7.1.0.Final','youtubeVideoUrl':'','recipeURL':'https://s3.amazonaws.com/cloudify-widget/2.7/jboss.zip','allowAnonymous':null,'apiKey':'19cc4c78-2f5f-11e3-9dfa-02163e4a1592','enabled':true,'recipeName':'jboss','requireLogin':false,'loginVerificationUrl':null,'webServiceKey':null,'lifeExpectancy':3600000,'description':'A recipe for JBoss 7.1.0.Final','consoleUrlService':null,'username':'hpdemo@gigaspaces.com','numOfInstances':2,'requiresLogin':false,'consolename':'JBoss Console','consoleurl':'http://$HOST:8080','rootpath':'','instances':[{'recipeType':'SERVICE','servicePublicIp':null,'installName':'jboss','link':{'title':'JBoss Console','url':'http://:8080'},'corrupted':false,'instanceId':null,'publicIP':null},{'recipeType':'SERVICE','servicePublicIp':null,'installName':'jboss','link':{'title':'JBoss Console','url':'http://:8080'},'corrupted':false,'instanceId':null,'publicIP':null}]},
                        {'id':1314,'productName':'Memcached','providerURL':'http://memcached.org','productVersion':'1.4.4-3.el6','title':'Memcached','youtubeVideoUrl':'','recipeURL':'https://s3.amazonaws.com/cloudify-widget/2.7/memcached.zip','allowAnonymous':null,'apiKey':'19cc4cfa-2f5f-11e3-9dfa-02163e4a1592','enabled':true,'recipeName':'memcached','requireLogin':false,'loginVerificationUrl':null,'webServiceKey':null,'lifeExpectancy':3600000,'description':'A recipe for MemcacheD which is an open source, distributed memory object caching system. ','consoleUrlService':null,'username':'hpdemo@gigaspaces.com','numOfInstances':0,'requiresLogin':false,'consolename':'Memcached','consoleurl':'http://$HOST:11211','rootpath':'','instances':[]},
                        {'id':1315,'productName':'Play Framework','providerURL':'http://www.playframework.com','productVersion':'2.0.3','title':'Play Framework','youtubeVideoUrl':'','recipeURL':'https://s3.amazonaws.com/cloudify-widget/2.7/computers.zip','allowAnonymous':null,'apiKey':'19cc4d86-2f5f-11e3-9dfa-02163e4a1592','enabled':true,'recipeName':'computers','requireLogin':false,'loginVerificationUrl':null,'webServiceKey':null,'lifeExpectancy':3600000,'description':'A recipe for the Play framework which is an open source web application framework.','consoleUrlService':'play','username':'hpdemo@gigaspaces.com','numOfInstances':0,'requiresLogin':false,'consolename':'Play Console','consoleurl':'http://$HOST:8080','rootpath':'apps/computers','instances':[]},
                        {'id':1316,'productName':'Vertx','providerURL':'http://vertx.io','productVersion':'1.2.3','title':'Vertx','youtubeVideoUrl':'','recipeURL':'https://s3.amazonaws.com/cloudify-widget/2.7/vertx.zip','allowAnonymous':null,'apiKey':'19cc4e12-2f5f-11e3-9dfa-02163e4a1592','enabled':true,'recipeName':'vertx','requireLogin':false,'loginVerificationUrl':null,'webServiceKey':null,'lifeExpectancy':3600000,'description':'A recipe for Vert.x which is an event driven application framework','consoleUrlService':null,'username':'hpdemo@gigaspaces.com','numOfInstances':0,'requiresLogin':false,'consolename':'Vertx Console','consoleurl':'http://$HOST:8080/','rootpath':'','instances':[]},
                        {'id':1317,'productName':'Drupal','providerURL':'http://drupal.org','productVersion':'7.*','title':'Drupal','youtubeVideoUrl':'','recipeURL':'https://s3.amazonaws.com/cloudify-widget/2.7/drupal.zip','allowAnonymous':null,'apiKey':'19cc4e9e-2f5f-11e3-9dfa-02163e4a1592','enabled':true,'recipeName':'babies','requireLogin':false,'loginVerificationUrl':null,'webServiceKey':null,'lifeExpectancy':3600000,'description':'A recipe for Drupal which is an open source content management platform','consoleUrlService':'drupal','username':'hpdemo@gigaspaces.com','numOfInstances':0,'requiresLogin':false,'consolename':'Drupal site','consoleurl':'http://$HOST:8080','rootpath':'apps/drupal-babies','instances':[]},
                        {'id':1318,'productName':'Cassandra','providerURL':'http://cassandra.apache.org/','productVersion':'0.8.7','title':'Cassandra','youtubeVideoUrl':'','recipeURL':'https://s3.amazonaws.com/cloudify-widget/2.7/cassandra.zip','allowAnonymous':null,'apiKey':'19cc4f2a-2f5f-11e3-9dfa-02163e4a1592','enabled':true,'recipeName':'cassandra','requireLogin':false,'loginVerificationUrl':null,'webServiceKey':null,'lifeExpectancy':3600000,'description':'A recipe for Cassandra which is a scalable and ha database.','consoleUrlService':null,'username':'hpdemo@gigaspaces.com','numOfInstances':0,'requiresLogin':false,'consolename':'Cassandra','consoleurl':'http://$HOST:9160','rootpath':'','instances':[]}
                    ],
                    'status': 200,
                    'config': {'method':'GET','url':'/backend/widgetslist'}
                };
        };

        this.getCatalogData = function() {
            return catalogData;
        };

        this.setCatalogData = function(data) {
            catalogData = data;
        };

        // Send selected widgets & catalog HTML to server
        this.sendCatalogData = function() {
            console.log(catalogData);
        };
    });
